[build]
  command = "npm install --production=false && npx vite build"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"
  NPM_FLAGS = "--production=false"
  NODE_VERSION = "20"

# Alternative build command if the main one fails
[build.processing]
  skip_processing = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 